/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sffortytwo;

import java.sql.DriverManager;
import java.sql.SQLException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        try {
            DriverManager.getConnection("", "scott", "tiger");
        } catch (SQLException sqle) {
            System.out.println("There was an error");
        }
    }
}
